import json
from datetime import date, timedelta

from tenacity import retry, stop_after_attempt, wait_fixed

from app.core.config import settings
from app.schemas.common import AIExtractionResponse, ExtractedTask


EXTRACTION_PROMPT = """
You are an enterprise PMO copilot. Extract task objects from the source content.
Return strict JSON with keys: tasks[], summary.
Each task object keys: action_item, responsible_person, deadline(YYYY-MM-DD or null), priority(high|medium|low), dependencies[], source_reference.
""".strip()


class AIEngine:
    @retry(stop=stop_after_attempt(2), wait=wait_fixed(1))
    def extract_tasks(self, source_text: str, source_reference: str) -> AIExtractionResponse:
        if settings.enable_mock_ai or not settings.openai_api_key:
            return self._mock_extract(source_text, source_reference)
        raise NotImplementedError("Wire your LLM provider SDK here for production deployment")

    def generate_mom(self, transcript: str) -> str:
        lines = [line.strip() for line in transcript.splitlines() if line.strip()]
        bullets = "\n".join(f"- {line}" for line in lines[:8])
        return f"Minutes of Meeting\n\nDiscussion Highlights:\n{bullets}\n\nDecisions & Actionables generated by AI PMO Copilot."

    def _mock_extract(self, source_text: str, source_reference: str) -> AIExtractionResponse:
        chunks = [c.strip("-• \t") for c in source_text.splitlines() if c.strip()]
        tasks = []
        for idx, chunk in enumerate(chunks[:6], start=1):
            tasks.append(
                ExtractedTask(
                    action_item=chunk,
                    responsible_person=None,
                    deadline=date.today() + timedelta(days=idx * 3),
                    priority="high" if "urgent" in chunk.lower() else "medium",
                    dependencies=[],
                    source_reference=source_reference,
                )
            )
        if not tasks:
            tasks = [
                ExtractedTask(
                    action_item="Review uploaded source and define next steps",
                    responsible_person=None,
                    deadline=date.today() + timedelta(days=5),
                    priority="medium",
                    dependencies=[],
                    source_reference=source_reference,
                )
            ]
        return AIExtractionResponse(tasks=tasks, summary=f"Extracted {len(tasks)} actions from source")


ai_engine = AIEngine()


def extraction_prompt_template() -> str:
    return json.dumps({"system_prompt": EXTRACTION_PROMPT}, indent=2)
